parameters:

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  keycloak.typo3.com.user.provider:
    class: '%t3g_keycloak.keycloak.user_provider_class%'
    arguments:
      $roleMapping: '%t3g_keycloak.keycloak.role_mapping%'
      $defaultRoles: '%t3g_keycloak.keycloak.default_roles%'

  keycloak.typo3.com.jwt.service:
    class: T3G\Bundle\Keycloak\Service\JWTService
    public: true
    arguments:
      $JWSVerifier: '@jose.jws_verifier.login_typo3_com'
      $JWKSet: '@jose.key_set.login_typo3_com'

  T3G\Bundle\Keycloak\Security\KeyCloakAuthenticator:
    class: T3G\Bundle\Keycloak\Security\KeyCloakAuthenticator
    public: true
