parameters:

services:
  keycloak.typo3.com.user.provider:
    class: '%t3g_keycloak.keycloak.user_provider_class%'
    arguments:

  T3G\Bundle\Keycloak\Service\JWTService:
    class: T3G\Bundle\Keycloak\Service\JWTService
    arguments:
      $JWSVerifier: '@jose.jws_verifier.login_typo3_com'
      $JWKSet: '@jose.key_set.login_typo3_com'