name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build-php:
    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} - Experimental ${{ matrix.experimental }}
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        symfony: ['^5.4', '^6.4']
        php: ['8.1', '8.2', '8.3']
        experimental: [false]
        include:
          - symfony: '^7.0'
            php: '8.2'
            experimental: true

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ matrix.php }}-composer-${{ matrix.symfony }}

      - name: Install
        run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony }}'"/' composer.json;
          composer update --prefer-dist --no-progress
          composer info
          git checkout composer.json

      - name: Lint
        run: composer t3g:test:php:lint

      - name: CGL
        run: composer t3g:cgl

      - name: Tests
        run: composer t3g:test:php

      - name: Git Status
        run: |
          git status
          git status | grep -q "nothing to commit, working tree clean"
